name: snapit-release
description: Create a snapshot NPM release with `/snapit` comment in a PR
author: Shopify
inputs:
  build_script:
    description: Build script for building the repository before publishing.
  post_install_script:
    description: Script to run after dependencies are installed.
  comment_command:
    description: A comma seperated list of comment commands to trigger the action
    default: '/snapit'
  branch:
    description: Push the changes to a branch instead of publishing to the NPM registry.
  custom_message_prefix:
    description: Custom message added to the beginning of the snapit GitHub comment. By default a generic message is shown.
  custom_message_suffix:
    description: Custom message added to the end of the snapit GitHub comment.
  global_install:
    description: If true, the GitHub comment will show instructions to install a global npm package instead of the normal JSON dependencies.
  github_comment_included_packages:
    description: Which packages to include in the final output. All pacakges are still published, but only those in this list are shown in the final message. If empty, all packages are included.
  working_directory:
    description: If specified, the action will run all commands for snapit in the specified directory.
  release_branch:
    description: If specified, will use this branch name in place of the default `changeset-release/main` branch.
    default: 'changeset-release/main'

runs:
  using: node20
  main: dist/index.js
branding:
  icon: aperture
  color: blue
