name: snapit-release
description: Create a snapshot NPM release with `/snapit` comment in a PR
author: Shopify
inputs:
  build_script:
    description: Build script for building the repository before publish to NPM
    required: true
runs:
  using: node20
  main: dist/index.js
branding:
  icon: aperture
  color: blue
