name: snapit-release
description: Create a snapshot NPM release with `/snapit` comment in a PR
author: Shopify
inputs:
  trigger_comment:
    description: A comma seperated list of comment commands to trigger the action
    default: '/snapit'
  comment_prefix:
    description: Custom message added to the beginning of the snapit GitHub comment. By default a generic message is shown.
  comment_suffix:
    description: Custom message added to the end of the snapit GitHub comment.
  comment_packages:
    description: Which packages to include in the final output. All pacakges are still published, but only those in this list are shown in the final message. If empty, all packages are included.
  comment_is_global:
    description: If true, the generated GitHub comment will show the command to install your packages globally. Otherwise, shows a JSON example to update local dependencies.
  cwd:
    description: If specified, the action will run all commands for snapit in the specified directory.
  branch:
    description: Push the changes to a branch instead of publishing to the NPM registry.
  build_script:
    description: Build script for building the repository before publishing.
  post_install_script:
    description: Script to run after dependencies are installed.
  release_branch:
    description: If specified, will use this branch name in place of the default `changeset-release/main` branch.
    default: 'changeset-release/main'

runs:
  using: node20
  main: dist/index.js
branding:
  icon: aperture
  color: blue
