name: Build action

on:
  push:
    branches:
      - main

jobs:
  build-action:
    name: Build GitHub Action
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Setup Node with v20.11.0
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build

      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
